In [49]:
import pandas as pd
import numpy as np
import os
import datetime

In [50]:
path = r'D:\Trabajo\Barómetro\BX\Web Scraping\Pie Charts Colombia\Historico hasta enero 26 2022' + '\\'

In [51]:
df = pd.read_excel(path + "archivo_0.xlsx", skiprows=9)
df

           all  all.1
0     Trabajo    2085
1   Xenofobia    2417
2        Mujer    519
3  Integración   2833
4   Educación     705
5   Seguridad    4448
6       Salud    1497

In [52]:
df.rename(columns= {"all": "Categoria", "all.1": "Volumen"}, inplace=True)

In [53]:
df

     Categoria  Volumen
0     Trabajo      2085
1   Xenofobia      2417
2        Mujer      519
3  Integración     2833
4   Educación       705
5   Seguridad      4448
6       Salud      1497

In [54]:
df.sum()[1]

14504

In [55]:
start_date = '2020-01-01' # YYYY-MM-DD
end_date = '2022-02-04' # PATTERN YYYY-MM-DD - YYYY-MM-DD
def next_week(fecha:str) -> str:
    nueva_fecha = datetime.datetime.strptime(fecha,'%Y-%m-%d').date()
    nueva_fecha = nueva_fecha + datetime.timedelta(days=7)
    return str(nueva_fecha)

def query_pie_chart(start_date: str, end_date: str) -> list:
    centinela = True
    retorno = list()
    two_weeks = next_week(next_week(start_date)) 
    n = 0
    while centinela == True:
        if n == 0:
            envio_range_fechas = start_date + " - " + two_weeks
            retorno.append(envio_range_fechas)
        else:
            start_date = two_weeks
            two_weeks = next_week(next_week(start_date))
            two_weeks_verif = datetime.datetime.strptime(two_weeks,'%Y-%m-%d').date()
            end_date_verif = datetime.datetime.strptime(end_date,'%Y-%m-%d').date()
            if int((end_date_verif - two_weeks_verif).days) < 0:
                centinela = False
            else:
                envio_range_fechas = start_date + " - " + two_weeks
                retorno.append(envio_range_fechas)
        n+=1
    return retorno
fechas = query_pie_chart(start_date, end_date)

In [76]:
final = pd.DataFrame()
for i in range(0,54):
    df = pd.read_excel(path + "archivo_" + str(i) + ".xlsx", skiprows=9)
    df.rename(columns= {"all": "Categoria", "all.1": "Volumen"}, inplace=True)
    dato = {'Categoria': 'Total', 'Volumen': df.sum()[1]}
    df = df.append(dato, ignore_index=True)
    df["Rango Fecha"] = fechas[i]
    final = final.append(df)

In [77]:
final

      Categoria  Volumen              Rango Fecha
0      Trabajo      2085  2020-01-01 - 2020-01-15
1    Xenofobia      2417  2020-01-01 - 2020-01-15
2         Mujer      519  2020-01-01 - 2020-01-15
3   Integración     2833  2020-01-01 - 2020-01-15
4    Educación       705  2020-01-01 - 2020-01-15
..          ...      ...                      ...
3   Integración     1058  2022-01-12 - 2022-01-26
4    Educación       687  2022-01-12 - 2022-01-26
5    Seguridad      3981  2022-01-12 - 2022-01-26
6        Salud      1080  2022-01-12 - 2022-01-26
7         Total    10472  2022-01-12 - 2022-01-26

[432 rows x 3 columns]

In [85]:
melteddf = final.pivot(index='Rango Fecha', columns=['Categoria'], values=['Volumen'])

In [86]:
melteddf

                           Volumen                                             \
Categoria               Educación  Integración Mujer Salud  Seguridad   Total
Rango Fecha
2020-01-01 - 2020-01-15        705        2833   519   1497       4448  14504
2020-01-15 - 2020-01-29       1058        3581   612   2449       5681  17916
2020-01-29 - 2020-02-12        976        2102   485   1351       5184  15067
2020-02-12 - 2020-02-26       1187        2481   444   2051       6250  20180
2020-02-26 - 2020-03-11       1080        1727   664   2385       4007  13692
2020-03-11 - 2020-03-25       1202        4094   527  16153      13910  48788
2020-03-25 - 2020-04-08       6677       13101  1121  24773      18271  83842
2020-04-08 - 2020-04-22        963        2635   449   9046       4124  21125
2020-04-22 - 2020-05-06        594        2336   348   4969       4828  17502
2020-05-06 - 2020-05-20        591        1551   349   4303       7007  17413
2020-05-20 - 2020-06-03        586        1817   398   3156       4629  14131
2020-06-03 - 2020-06-17        575        1372   543   2281       4158  12960
2020-06-17 - 2020-07-01        598        1608   701   2298       5180  13975
2020-07-01 - 2020-07-15        635        2363   458   2840       8500  19277
2020-07-15 - 2020-07-29        856         945   436   2708       4481  12538
2020-07-29 - 2020-08-12       1021        1106   430   1776       3154  10626
2020-08-12 - 2020-08-26        556        1266   410   1949       3463  10988
2020-08-26 - 2020-09-09        504         744   311   1849       3941   9743
2020-09-09 - 2020-09-23       1133        1119   381   1777       6325  15066
2020-09-23 - 2020-10-07        835        1136   392   1403       3790  10359
2020-10-07 - 2020-10-21        979        1661   406   1750       3714  12575
2020-10-21 - 2020-11-04       1014       10357   589   3354      20340  43806
2020-11-04 - 2020-11-18        818        3297   361   2101       7069  17640
2020-11-18 - 2020-12-02        746        1724   375   1875       3714  11379
2020-12-02 - 2020-12-16        697        1366   407   1487       3640  10266
2020-12-16 - 2020-12-30        743        2261   253  11154       3664  23681
2020-12-30 - 2021-01-13        511         789   279   2257       2334   8925
2021-01-13 - 2021-01-27        682         924   422   3128       3446  11778
2021-01-27 - 2021-02-10       2062        8713   400   3663       9422  39634
2021-02-10 - 2021-02-24       1507        4192   318   3222       6304  22168
2021-02-24 - 2021-03-10        964        2730   388   1770       3724  14668
2021-03-10 - 2021-03-24       1434       12242  1357   3522      23832  51057
2021-03-24 - 2021-04-07        737        2047   370   2899       6423  15783
2021-04-07 - 2021-04-21       1016        1621   331   2175       3954  12116
2021-04-21 - 2021-05-05        924        2212   425   4132       9422  24431
2021-05-05 - 2021-05-19        910        2174   367   1432       7194  16794
2021-05-19 - 2021-06-02        978        1579   275   1600       5653  14731
2021-06-02 - 2021-06-16        704        2158   249   1780       4503  14131
2021-06-16 - 2021-06-30        872        1363   377   1580       3312  10657
2021-06-30 - 2021-07-14        761        1199   602   1520       9549  19383
2021-07-14 - 2021-07-28        526        1106   355   1904       6542  14073
2021-07-28 - 2021-08-11        691        2138   609   1700       5453  14339
2021-08-11 - 2021-08-25        705        5715   906   1805      13767  31016
2021-08-25 - 2021-09-08        963        1319   480   1697       5146  12831
2021-09-08 - 2021-09-22        844        1872   308   1335       5646  13801
2021-09-22 - 2021-10-06        822        1956   407   1294       3965  13071
2021-10-06 - 2021-10-20        882        3045   311   1692       8616  18796
2021-10-20 - 2021-11-03       1012        1273   358   1938       3565  11969
2021-11-03 - 2021-11-17        815         847   298   1608       3736  10585
2021-11-17 - 2021-12-01       1049         962   310   1169       2892   8915
2021-12-01 - 2021-12-15       1006         977   335   1166       4420  11017
2021-12-15 - 2021-12-29        895        2260   273    950       2713  10306
2021-12-29 - 2022-01-12        517        1064   261   1445       6227  14123
2022-01-12 - 2022-01-26        687        1058   300   1080       3981  10472


Categoria               Trabajo  Xenofobia
Rango Fecha
2020-01-01 - 2020-01-15     2085       2417
2020-01-15 - 2020-01-29     1645       2890
2020-01-29 - 2020-02-12     1722       3247
2020-02-12 - 2020-02-26     3492       4275
2020-02-26 - 2020-03-11     1484       2345
2020-03-11 - 2020-03-25     4687       8215
2020-03-25 - 2020-04-08     9961       9938
2020-04-08 - 2020-04-22     1490       2418
2020-04-22 - 2020-05-06     1352       3075
2020-05-06 - 2020-05-20     1217       2395
2020-05-20 - 2020-06-03     1283       2262
2020-06-03 - 2020-06-17     1123       2908
2020-06-17 - 2020-07-01     1145       2445
2020-07-01 - 2020-07-15     1234       3247
2020-07-15 - 2020-07-29     1383       1729
2020-07-29 - 2020-08-12     1327       1812
2020-08-12 - 2020-08-26     1483       1861
2020-08-26 - 2020-09-09      827       1567
2020-09-09 - 2020-09-23     1129       3202
2020-09-23 - 2020-10-07      945       1858
2020-10-07 - 2020-10-21     1310       2755
2020-10-21 - 2020-11-04     2203       5949
2020-11-04 - 2020-11-18     1383       2611
2020-11-18 - 2020-12-02     1164       1781
2020-12-02 - 2020-12-16      846       1823
2020-12-16 - 2020-12-30     2407       3199
2020-12-30 - 2021-01-13     1086       1669
2021-01-13 - 2021-01-27     1163       2013
2021-01-27 - 2021-02-10     9904       5470
2021-02-10 - 2021-02-24     3731       2894
2021-02-24 - 2021-03-10     3185       1907
2021-03-10 - 2021-03-24     3709       4961
2021-03-24 - 2021-04-07     1355       1952
2021-04-07 - 2021-04-21     1198       1821
2021-04-21 - 2021-05-05     3528       3788
2021-05-05 - 2021-05-19     1544       3173
2021-05-19 - 2021-06-02     1260       3386
2021-06-02 - 2021-06-16     1495       3242
2021-06-16 - 2021-06-30     1352       1801
2021-06-30 - 2021-07-14     3707       2045
2021-07-14 - 2021-07-28     1620       2020
2021-07-28 - 2021-08-11     1364       2384
2021-08-11 - 2021-08-25     3191       4927
2021-08-25 - 2021-09-08     1555       1671
2021-09-08 - 2021-09-22     1602       2194
2021-09-22 - 2021-10-06     1206       3421
2021-10-06 - 2021-10-20     2067       2183
2021-10-20 - 2021-11-03     1817       2006
2021-11-03 - 2021-11-17     1404       1877
2021-11-17 - 2021-12-01     1247       1286
2021-12-01 - 2021-12-15     1468       1645
2021-12-15 - 2021-12-29     1443       1772
2021-12-29 - 2022-01-12     1397       3212
2022-01-12 - 2022-01-26     1400       1966

In [87]:
melteddf.columns = melteddf.columns.droplevel()
melteddf.head(5)

Categoria,Educación,Integración,Mujer,Salud,Seguridad,Total,Trabajo,Xenofobia
Rango Fecha,,,,,,,,
2020-01-01 - 2020-01-15,705,2833,519,1497,4448,14504,2085,2417
2020-01-15 - 2020-01-29,1058,3581,612,2449,5681,17916,1645,2890
2020-01-29 - 2020-02-12,976,2102,485,1351,5184,15067,1722,3247
2020-02-12 - 2020-02-26,1187,2481,444,2051,6250,20180,3492,4275
2020-02-26 - 2020-03-11,1080,1727,664,2385,4007,13692,1484,2345

In [89]:
columns_list = melteddf.columns
columns_list = columns_list.drop('Total')
for i in range(len(columns_list)):
    texto = str(columns_list[i]).strip()
    melteddf[texto + " %"] = melteddf[columns_list[i]]/melteddf['Total']
melteddf.head(5)

Categoria,Educación,Integración,Mujer,Salud,Seguridad,Total,Trabajo,Xenofobia,Educación %,Integración %,Mujer %,Salud %,Seguridad %,Trabajo %,Xenofobia %
Rango Fecha,,,,,,,,,,,,,,,
2020-01-01 - 2020-01-15,705,2833,519,1497,4448,14504,2085,2417,0.048607,0.195325,0.035783,0.103213,0.306674,0.143753,0.166644
2020-01-15 - 2020-01-29,1058,3581,612,2449,5681,17916,1645,2890,0.059053,0.199877,0.034159,0.136693,0.317091,0.091817,0.161308
2020-01-29 - 2020-02-12,976,2102,485,1351,5184,15067,1722,3247,0.064777,0.139510,0.032190,0.089666,0.344063,0.114290,0.215504
2020-02-12 - 2020-02-26,1187,2481,444,2051,6250,20180,3492,4275,0.058821,0.122944,0.022002,0.101635,0.309713,0.173043,0.211843
2020-02-26 - 2020-03-11,1080,1727,664,2385,4007,13692,1484,2345,0.078878,0.126132,0.048495,0.174189,0.292653,0.108384,0.171268

In [90]:
melteddf.to_excel("Histórico_Pie_Charts.xlsx")